import os

DB_NAME = "pygr"
DB_HOST_DEV = "localhost"
DB_PORT_DEV = "5433"
DB_USER_DEV = "postgres"
DB_PASSWORD_DEV = "25898"

INTERNAL_LOADED_URL_LOCATOR_TYPE = "loaded_url"
INTERNAL_STARTING_URL_LOCATOR_TYPE = "starting_url"
INTERNAL_DATETIME_URL_LOCATOR_TYPE = "datetime"
XPATH_LOCATOR_TYPE = "XPATH"
CSS_LOCATOR_TYPE = "CSS"

BROWSER_MODE = "BROWSER"
CRAWLER_MODE = "CRAWLER"

URL_LIST_TYPE = "list"

EXCEL_EXPORT_FORMAT = "EXCEL"
CSV_EXPORT_FORMAT = "CSV"
EXPORT_FORMATS = ["CSV", "EXCEL"]

GRABBER_TYPE = "grabber"
GRABBER_LIST_TYPE = "grabber_list"
GRABBER_INTERNAL_TYPE = "grabber_internal"
PAGINATION_TYPE = "pagination"
NAVIGATION_TYPE = "navigation"

ITEMS_THAT_EXPORT = [GRABBER_TYPE, GRABBER_INTERNAL_TYPE]

CLICK_ACTION = "click"
LOAD_URL_ACTION = "load_url"

DEFAULT_EXPORT_ENCODING = "utf8"
DEFAULT_DATETIME_FORMAT = "%m/%d/%Y %H:%M:%S:%f"

REGEX_TR_TYPE = "regex"

LOGS_FILE_PATH = "logs"
LOG_SEPARATOR = "--------------------------------------------------------------------------------------------------"

